// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace PFAssist.UI.iOS
{
	public partial class CharacterDetailsViewController : UIViewController
	{
		public CharacterDetailsViewController (IntPtr handle) : base (handle)
		{
		}

		partial void Cancel (NSObject sender)
		{
			DismissViewControllerAsync(true);
		}

		partial void Save (NSObject sender)
		{
			DismissViewControllerAsync(true);
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);

			var titleTextAttributes = NavigationController.NavigationBar.GetTitleTextAttributes();
			titleTextAttributes.TextColor = UIColor.White;

			NavigationController.NavigationBar.SetBackgroundImage (new UIImage (), UIBarMetrics.Default);
			NavigationController.NavigationBar.ShadowImage = new UIImage ();
			NavigationController.NavigationBar.Translucent = true;
			NavigationController.NavigationBar.SetTitleTextAttributes(titleTextAttributes);

			tableView.BackgroundColor = UIColor.Clear;
		}
	}
}
