// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using ReactiveUI.Cocoa;
using ReactiveUI;
using System.Drawing;

namespace PFAssist.UI.iOS
{
	public partial class SimpleStatViewCell : ReactiveTableViewCell, IViewFor<SimpleStatViewModel>
	{
		// Fields
		private SimpleStatViewModel viewModel;

		// Constructors
		public SimpleStatViewCell (IntPtr handle) : base (handle)
		{
			BackgroundColor = new UIColor(0f, 0f, 0f, 0.2f);

			TextLabel.BackgroundColor = UIColor.Clear;
			DetailTextLabel.BackgroundColor = UIColor.Clear;
		}

		// Methods
		public void BindToViewModel()
		{
			TextLabel.Text = viewModel.Description;
			viewModel.Data.BindTo (DetailTextLabel, d => d.Text);
		}

		#region IViewFor implementation

		public SimpleStatViewModel ViewModel {
			get {
				return viewModel;
			}
			set {
				viewModel = value;
			}
		}

		#endregion

		#region IViewFor implementation

		object IViewFor.ViewModel {
			get {
				return viewModel;
			}
			set {
				viewModel = value as SimpleStatViewModel;
			}
		}

		#endregion
	}
}
